{{- if and (not .Values.secret.db.secretRef) .Values.db.enableLegacy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.db" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.db.legacy.secret.db }}
{{- if $value }}
{{- if or (eq (typeOf $value) "string") (eq (typeOf $value) "numeric") }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
  password_encoded: {{ .Values.db.legacy.secret.db.password | urlquery | b64enc }}
{{- end }}
