{{- if .Values.db.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.roles" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  authenticator: {{ .Values.secret.db.password | b64enc | quote }}
  pgbouncer: {{ .Values.secret.db.password | b64enc | quote }}
  supabase_auth_admin: {{ .Values.secret.db.password | b64enc | quote }}
  supabase_functions_admin: {{ .Values.secret.db.password | b64enc | quote }}
  supabase_storage_admin: {{ .Values.secret.db.password | b64enc | quote }}
{{- end }}
