{{- if and .Values.db.enabled .Values.db.backup.enabled .Values.db.enableCNPG (not .Values.db.backup.s3.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.cnpg.backupSecret" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  ACCESS_KEY_ID: {{ .Values.db.backup.s3.accessKeyId | b64enc | quote }}
  ACCESS_SECRET_KEY: {{ .Values.db.backup.s3.secretAccessKey | b64enc | quote }}
{{- end }}
