{{- if .Values.db.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.initdb.secret" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-config.sql: |
    -- Create _analytics schema
    CREATE SCHEMA IF NOT EXISTS _analytics;
    ALTER SCHEMA _analytics OWNER TO supabase_admin;

    -- Create _realtime schema
    CREATE SCHEMA IF NOT EXISTS _realtime;
    ALTER SCHEMA _realtime OWNER TO supabase_admin;

    -- Configure JWT application settings
    ALTER DATABASE {{ .Values.secret.db.database | default "supabase" }} SET "app.settings.jwt_secret" TO '{{ .Values.secret.jwt.secret }}';
    ALTER DATABASE {{ .Values.secret.db.database | default "supabase" }} SET "app.settings.jwt_exp" TO '{{ .Values.db.environment.JWT_EXP | default 3600 }}';
{{- end }}
