{{- if .Values.db.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.initdb.configmap" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  00-custom.sql: |
{{ .Files.Get "initdb-sql/00-custom.sql" | indent 4 }}
  10-initial-schema.sql: |
{{ .Files.Get "initdb-sql/10-initial-schema.sql" | indent 4 }}
  11-auth-schema.sql: |
{{ .Files.Get "initdb-sql/11-auth-schema.sql" | indent 4 }}
  12-storage-schema.sql: |
{{ .Files.Get "initdb-sql/12-storage-schema.sql" | indent 4 }}
  13-post-setup.sql: |
{{ .Files.Get "initdb-sql/13-post-setup.sql" | indent 4 }}
  14-webhooks.sql: |
{{ .Files.Get "initdb-sql/14-webhooks.sql" | indent 4 }}
{{- end }}
