apiVersion: v1
kind: Secret
metadata:
  name: supabase-db-postgres
  namespace: supabase
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: "123123123"  # Replace with actual password
