{{- if .Values.db.enableCNPG }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-postgres
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.secret.db.superuser.username | b64enc }}
  password: {{ .Values.secret.db.superuser.password | b64enc }}
{{- end }}