apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-postgres
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: "123123123"  # Replace with actual password
