apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-supabase-admin
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: supabase_admin
  password: "example123456"
  database: supabase
