apiVersion: v1
kind: Secret
metadata:
  name: supabase-db-supabase-admin
  namespace: supabase
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: supabase_admin
  password: "example123456"
